[package]
name = "delta-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.3"
indexmap = "2.2.5"
ordered-float = "4.0"
roaring = "0.10.3"
time = { version = "0.3.34", features = ["parsing"] }

[dev-dependencies]
lazy_static = "1.4.0"
rand = "0.8.5"
