[package]
name = "delta-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "2.2.2"
roaring = "0.10.2"
time = "0.3.34"
ordered-float = "4.0"

[dev-dependencies]
lazy_static = "1.4.0"