[package]
name = "delta-search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.3"
heed = "0.11.0"
indexmap = { version = "2.2.5", features = ["serde"] }
ordered-float = { version = "4.0", features = ["serde"] }
roaring = { version = "0.10.3", features = ["serde"] }
time = { version = "0.3.34", features = ["parsing"] }
serde = { version = "1.0.196", features = ["derive"] }

[dev-dependencies]
lazy_static = "1.4.0"
rand = "0.8.5"

[features]
test-fixtures = []

[profile.bench]
lto = "thin"
debug = true

